### ISSUE TITLE
missing directory

### ISSUE THREAD

**Issue by MindFluid** [akpakshendra/Serene-Conky#5]
Everything works fine except for the weather and quote sections. I've entered in my api, but I get this error for the quote and the weather .cml. Where do I get these?
`IOError: [Errno 2] No such file or directory: 'Downloads/quote.cml'`

**Comment by FrdVnW** [comment]
Create 'Downloads', and don't run 'setup.sh', which remove this folder

**Comment by akshendra** [comment]
@MindFluid this should be fixed thanks to @FrdVnW.
